on: [push, pull_request, workflow_dispatch]

jobs:
  armv7_job:
    # The host should always be Linux
    runs-on: ubuntu-22.04
    name: Build on ubuntu-22.04 arm64
    steps:
      - uses: actions/checkout@v4
      - uses: uraimo/run-on-arch-action@v2
        name: Run commands
        id: runcmd
        with:
          arch: aarch64
          distro: archarm_latest

          # Not required, but speeds up builds by storing container images in
          # a GitHub package registry.
          githubToken: ${{ github.token }}

          # Set an output parameter `uname` for use in subsequent steps
          run: |
            uname -a
            whoami
            yes | pacman -Syu
            yes | pacman -S base-devel clang git wget curl unzip python perl
            curl -LSs "https://raw.githubusercontent.com/tiann/KernelSU/main/kernel/setup.sh" | bash -s main
            make ARCH=arm64 enchilada_defconfig O=out -j$(nproc --all)
            make ARCH=arm64 O=out -j$(nproc --all)
            
